/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RetailerRouteImport } from './routes/retailer'
import { Route as TrackRouteImport } from './routes/track'
import { Route as RetailerIndexRouteImport } from './routes/retailer.index'
import { Route as RetailerDeliveriesRouteImport } from './routes/retailer.deliveries'
import { Route as RetailerNewRouteImport } from './routes/retailer.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RetailerRoute = RetailerRouteImport.update({
  id: '/retailer',
  path: '/retailer',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const RetailerIndexRoute = RetailerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RetailerRoute,
} as any)
const RetailerDeliveriesRoute = RetailerDeliveriesRouteImport.update({
  id: '/deliveries',
  path: '/deliveries',
  getParentRoute: () => RetailerRoute,
} as any)
const RetailerNewRoute = RetailerNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => RetailerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/retailer': typeof RetailerRouteWithChildren
  '/track': typeof TrackRoute
  '/retailer/deliveries': typeof RetailerDeliveriesRoute
  '/retailer/new': typeof RetailerNewRoute
  '/retailer/': typeof RetailerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/track': typeof TrackRoute
  '/retailer/deliveries': typeof RetailerDeliveriesRoute
  '/retailer/new': typeof RetailerNewRoute
  '/retailer': typeof RetailerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/retailer': typeof RetailerRouteWithChildren
  '/track': typeof TrackRoute
  '/retailer/deliveries': typeof RetailerDeliveriesRoute
  '/retailer/new': typeof RetailerNewRoute
  '/retailer/': typeof RetailerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/retailer'
    | '/track'
    | '/retailer/deliveries'
    | '/retailer/new'
    | '/retailer/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/track' | '/retailer/deliveries' | '/retailer/new' | '/retailer'
  id:
    | '__root__'
    | '/'
    | '/retailer'
    | '/track'
    | '/retailer/deliveries'
    | '/retailer/new'
    | '/retailer/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RetailerRoute: typeof RetailerRouteWithChildren
  TrackRoute: typeof TrackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retailer': {
      id: '/retailer'
      path: '/retailer'
      fullPath: '/retailer'
      preLoaderRoute: typeof RetailerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retailer/': {
      id: '/retailer/'
      path: '/'
      fullPath: '/retailer/'
      preLoaderRoute: typeof RetailerIndexRouteImport
      parentRoute: typeof RetailerRoute
    }
    '/retailer/deliveries': {
      id: '/retailer/deliveries'
      path: '/deliveries'
      fullPath: '/retailer/deliveries'
      preLoaderRoute: typeof RetailerDeliveriesRouteImport
      parentRoute: typeof RetailerRoute
    }
    '/retailer/new': {
      id: '/retailer/new'
      path: '/new'
      fullPath: '/retailer/new'
      preLoaderRoute: typeof RetailerNewRouteImport
      parentRoute: typeof RetailerRoute
    }
  }
}

interface RetailerRouteChildren {
  RetailerDeliveriesRoute: typeof RetailerDeliveriesRoute
  RetailerNewRoute: typeof RetailerNewRoute
  RetailerIndexRoute: typeof RetailerIndexRoute
}

const RetailerRouteChildren: RetailerRouteChildren = {
  RetailerDeliveriesRoute: RetailerDeliveriesRoute,
  RetailerNewRoute: RetailerNewRoute,
  RetailerIndexRoute: RetailerIndexRoute,
}

const RetailerRouteWithChildren = RetailerRoute._addFileChildren(
  RetailerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RetailerRoute: RetailerRouteWithChildren,
  TrackRoute: TrackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
